//
//  BDSSpeechSynthesizerDelegate.h
//  BDSSpeechSynthesizer
//
//  Created by  段弘 on 13-11-23.
//  Copyright (c) 2013年 百度. All rights reserved.
//

#import <Foundation/Foundation.h>
@class BDSSpeechSynthesizer;

typedef enum BDSAudioPlayerPauseSources
{
    BDS_AUDIO_PLAYER_PAUSE_SOURCE_USER,
    BDS_AUDIO_PLAYER_PAUSE_SOURCE_AUDIO_INTERRUPT,
    BDS_AUDIO_PLAYER_PAUSE_SOURCE_ENTERED_BACKGROUND
}BDSAudioPlayerPauseSources;

typedef enum BDSAudioFormat{
    BDS_AUDIO_FORMAT_PCM_8K = 0,
    BDS_AUDIO_FORMAT_PCM_16K = 1,
    BDS_AUDIO_FORMAT_MP3 = 2
}BDSAudioFormat;

@protocol BDSSpeechSynthesizerDelegate <NSObject>

/**
 * @brief 合成器开始工作
 *
 * @param speechSynthesizer 合成器对象
 */
@optional
/**
 * @brief Began synthesizing new sentence.
 *        NOTE: Will receive one call for each sentence
 *
 * @param SynthesizeSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences- and queueSynthesizeSentences-interface.
 *        (Indicates index of sentence if old deprecated synthesize-, speak-,
 *          batchSpeak- or batchSynthesize-  interfaces have been used)
 *        NOTE: SynthesizeSentence may be any value from NSInteger's value
 *        range, including negative values but excluding -1, which is reserved to
 *        indicate none.
 */
- (void)synthesizerStartWorkingSentence:(NSInteger)SynthesizeSentence;

/**
 * @brief Finished synthesizing a sentence.
 *        NOTE: Will receive one call for each sentence
 *
 * @param SynthesizeSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences- and queueSynthesizeSentences-interface.
 *        (Indicates index of sentence if old deprecated synthesize-, speak-,
 *          batchSpeak- or batchSynthesize-  interfaces have been used)
 *        NOTE: SynthesizeSentence may be any value from NSInteger's value
 *        range, including negative values but excluding -1, which is reserved to
 *        indicate none.
 */
- (void)synthesizerFinishWorkingSentence:(NSInteger)SynthesizeSentence;

/**
 * @brief Began speak a sentence.
 *        NOTE: Will receive one call for each sentenceNumber
 *        Not called if only synthesizing
 *
 * @param SpeakSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences-interface.
 *        (Indicates index of sentence if old deprecated speak- or
 *          batchSpeak-interfaces have been used)
 *        NOTE: SpeakSentence may be any value from NSInteger's value
 *        range, including negative values but excluding -1, which is reserved to
 *        indicate none.
 */
- (void)synthesizerSpeechStartSentence:(NSInteger)SpeakSentence;
/**
 * @brief 朗读完成
 *        NOTE: Will receive one call for each sentenceNumber
 *        Not called if only synthesizing
 *
 * @param SpeakSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences-interface.
 *        (Indicates index of sentence if old deprecated speak- or
 *          batchSpeak-interfaces have been used)
 *        NOTE: SpeakSentence may be any value from NSInteger's value
 *        range, including negative values but excluding -1, which is reserved to
 *        indicate none.
 */
- (void)synthesizerSpeechEndSentence:(NSInteger)SpeakSentence;

/**
 * @brief 新的语音数据已经合成
 *
 * @param newData 语音数据
 * @param fmt Audio format in passed buffer.
 * @param newLength Currently synthesized character count of current sentence
 *        to get total character count, you must add lengths of all sentences
 *        up to sentence-1，取值范围[0, [text length]]
 * @param SynthesizeSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences- and queueSynthesizeSentences-interface.
 *        (Indicates index of sentence if old deprecated synthesize-, speak-,
 *          batchSpeak- or batchSynthesize-  interfaces have been used)
 *        NOTE: SynthesizeSentence may be any value from NSInteger's value
 *        range, including negative values but excluding -1, which is reserved to
 *        indicate none.
 */
- (void)synthesizerNewDataArrived:(NSData *)newData
                       DataFormat:(BDSAudioFormat)fmt
                   characterCount:(int)newLength
                   sentenceNumber:(NSInteger)SynthesizeSentence;


/**
 * @brief Gives an estimation about how many characters have been spoken so far.
 *        Not called if only synthesizing
 *
 * @param length Currently finished speaking character count of current sentence
 *        to get total character count, you must add lengths of all sentences
 *        up to sentence-1，取值范围[0, [text length]]
 * @param SpeakSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences-interface.
 *        (Indicates index of sentence if old deprecated speak- or
 *          batchSpeak-interfaces have been used)
 *        NOTE: SpeakSentence may be any value from NSInteger's value
 *        range, including negative values but excluding -1, which is reserved to
 *        indicate none.
 */
- (void)synthesizerTextSpeakLengthChanged:(int)newLength
                           sentenceNumber:(NSInteger)SpeakSentence;

/**
 * @brief invoked when player gets paused
 * @param src, what caused the pause.
 */
- (void)synthesizerPaused:(BDSAudioPlayerPauseSources)src;

/**
 * @brief invoked when player is resumed from pause
 */
- (void)synthesizerResumed;

/**
 * @brief 合成器发生错误
 *
 * @param error 错误对象
 * @param SpeakSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences-interface.
 *        (Indicates index of sentence if old deprecated speak- or
 *          batchSpeak-interfaces have been used)
 *
 * @param SynthesizeSentence Sentence ID generated BY SDK and returned by
 *        queueSpeakSentences- and queueSynthesizeSentences-interface.
 *        (Indicates index of sentence if old deprecated synthesize-, speak-,
 *          batchSpeak- or batchSynthesize-  interfaces have been used)
 *        NOTE: SpeakSentence may be any value from NSInteger's value
 *        range, including negative values, also -1 may be encountered in this callback
 *        if error happened while only synthesizing or playback haven't started yet.
 *        NOTE: SynthesizeSentence may be any value from NSInteger's value
 *        range, including negative values, also -1 may be encountered in this callback
 *        if error happened in player and synthesizer had already finished it's work.
 */
- (void)synthesizerErrorOccurred:(NSError *)error
                        speaking:(NSInteger)SpeakSentence
                    synthesizing:(NSInteger)SynthesizeSentence;

@end